// Generates docs/rules.md from the rule metadata in dist/ (run `npm run docs`).
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { RULES } from '../dist/index.js';

const out = fileURLToPath(new URL('../docs/rules.md', import.meta.url));
const SEV = { critical: '🔴 critical', high: '🟠 high', medium: '🟡 medium', low: '🔵 low' };
const KIND = {
  skill: 'SKILL.md',
  'skill-doc': 'skill docs',
  script: 'skill/hook scripts',
  instructions: 'instruction files',
  markdown: 'markdown (--all-md)',
  'claude-settings': 'Claude settings',
  'mcp-config': 'MCP configs',
  'claude-json': '~/.claude.json',
  'codex-config': 'Codex config.toml',
};

const lines = [
  '# promptwarden rules',
  '',
  '<!-- This file is generated by `npm run docs` from src/rules/meta.ts. Do not edit by hand. -->',
  '',
  `promptwarden ships ${RULES.length} rules. Every finding links here. Severities are defaults; some rules raise or lower`,
  'severity for a specific finding (for example, quoted examples are downgraded and injection combined with hidden content is escalated).',
  '',
  'Suppress a single finding with `<!-- promptwarden-ignore PW0xx -->` (markdown) or `# promptwarden-ignore PW0xx` (scripts/TOML)',
  'on the same or the previous line, a whole file with `promptwarden-ignore-file PW0xx`, or paths via `.promptwardenignore`.',
  '',
  '| ID | Severity | Category | Title |',
  '| --- | --- | --- | --- |',
  ...RULES.map((r) => `| [${r.id}](#${r.id.toLowerCase()}-${r.name}) | ${SEV[r.severity]} | ${r.category} | ${r.title} |`),
  '',
];
for (const r of RULES) {
  lines.push(
    `## ${r.id} ${r.name}`,
    '',
    `**${r.title}**`,
    '',
    `- Severity: ${SEV[r.severity]}`,
    `- Category: \`${r.category}\``,
    `- Applies to: ${[...new Set(r.appliesTo.map((k) => KIND[k] ?? k))].join(', ')}`,
    '',
    r.description,
    '',
  );
  if (r.examples?.length) {
    lines.push('Examples that trigger it:', '', '```text', ...r.examples, '```', '');
  }
  lines.push(`**Remediation:** ${r.remediation}`, '', '[↑ back to index](#promptwarden-rules)', '');
}
writeFileSync(out, lines.join('\n'));
console.log(`wrote ${out} (${RULES.length} rules)`);
